AIR_POLLUTION_URL = 'http://api.openweathermap.org/data/2.5/air_pollution?'
AIR_POLLUTION_HISTORY_URL = 'http://api.openweathermap.org/data/2.5/air_pollution/history?'
WEATHER_CURRENT_URL = 'http://api.openweathermap.org/data/2.5/weather?'
WEATHER_DAILY_FORECAST_URL = 'http://api.openweathermap.org/data/2.5/forecast/daily?'
GEO_DIRECT_URL = 'http://api.openweathermap.org/geo/1.0/direct?'